### ISSUE TITLE
Coral Reef Models

### ISSUE THREAD

**Issue by Zulban** [osmosacademy/vr-campaign#11]
Model and texture low poly coral reefs. Create many (20?) different models, very differently shaped. Their textures should be colourful and very different. Make a coral reefs folder in the meshes folder, and put them there. Git push if you know how, or ask for help to share the files.

**vr-campaign/Assets/Meshes/coral-reefs/**

**Comment by Zulban** [comment]
It would be of enormous help if you or someone could take a crack at this, even partially, today or tomorrow.

**Comment by Zulban** [comment]
@peterwilkinson I have a strange feeling that it may be better performance wise to decorate the scene with very low poly 3D corals, that have non-transparent textures and normal maps.

**Comment by peterwilkinson** [comment]
You're right on that @Zulban . Where ever we can save a bit on performance. I guess its checking the poly count vs textures/shaders to strike the balance.

**Comment by Zulban** [comment]
Yeah 3D models fill the screen much better. Even on my PC I can feel a big performance improvement with the same number of polygons for 2D versus 3D. I think transparent textures are brutal to render.

It's not 20 nice models but here we go:

![3d-corals](https://cloud.githubusercontent.com/assets/1461690/14200674/6e639c52-f7ba-11e5-858c-84d8bf81ab68.png)
